require 'neovim.options'
require 'neovim.plugins'
require 'neovim.keymaps'
require 'neovim.completion'
require 'neovim.lsp'
require 'neovim.telescope'
require 'neovim.treesitter'
require 'neovim.autopairs'
